server:
  port: 8084

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/ai_capability_mapping
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.trae.adminservice.entity

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: 86400